version: '3'
services:
  dressings_manager_service:
    container_name: dressings_manager_service
    image: dressings-manager-service:latest
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ../../.prod.env
    networks:
      - ace_network
    depends_on:
      - "dressings_manager_service_mongodb"

  dressings_manager_service_mongodb:
    container_name: dressings_manager_service_mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - dressings_manager_service_mongodb_volume:/data/db
    networks:
      - ace_network

networks:
  ace_network:
      driver: bridge

volumes:
  dressings_manager_service_mongodb_volume:
